# Generated by Django 4.2.16 on 2026-02-17 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("outbreaks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the update", max_length=200),
                ),
                ("content", models.TextField(help_text="Full content of the update")),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("announcement", "Official Announcement"),
                            ("guideline", "Control Measure / Guideline"),
                            ("alert", "Alert / Warning"),
                        ],
                        default="news",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this update was published",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        default="Ministry of Agriculture",
                        help_text="Source of the update",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for the update",
                        null=True,
                        upload_to="updates/images/",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Optional document attachment (PDF, etc.)",
                        null=True,
                        upload_to="updates/documents/",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Is this update visible to the public?"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this update on the homepage?"
                    ),
                ),
                (
                    "related_outbreak",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a specific outbreak if relevant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updates",
                        to="outbreaks.outbreak",
                    ),
                ),
            ],
            options={
                "verbose_name": "Update",
                "verbose_name_plural": "Updates",
                "ordering": ["-published_at"],
            },
        ),
    ]
