# Generated by Django 4.2.16 on 2026-02-17 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Outbreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for the outbreak (e.g., 'Manzini Region Outbreak - Jan 2024')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the outbreak"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active Outbreak"),
                            ("surveillance", "Under Surveillance"),
                            ("cleared", "Cleared/Controlled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("hhohho", "Hhohho"),
                            ("manzini", "Manzini"),
                            ("lubombo", "Lubombo"),
                            ("shiselweni", "Shiselweni"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Latitude coordinate", max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Longitude coordinate", max_digits=9
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text="Name of the specific location/farm", max_length=200
                    ),
                ),
                (
                    "animals_affected",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of animals affected"
                    ),
                ),
                (
                    "animals_quarantined",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of animals under quarantine"
                    ),
                ),
                (
                    "date_reported",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the outbreak was first reported",
                    ),
                ),
                (
                    "date_confirmed",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the outbreak was officially confirmed",
                        null=True,
                    ),
                ),
                (
                    "date_cleared",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the outbreak was declared cleared",
                        null=True,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        default="Ministry of Agriculture",
                        help_text="Source of the outbreak information",
                        max_length=200,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this outbreak been verified by authorities?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this record active in the system?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbreak",
                "verbose_name_plural": "Outbreaks",
                "ordering": ["-date_reported"],
            },
        ),
    ]
