# Generated by Django 4.2.16 on 2026-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbreaks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DipTank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the dip tank location", max_length=200
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("hhohho", "Hhohho"),
                            ("manzini", "Manzini"),
                            ("lubombo", "Lubombo"),
                            ("shiselweni", "Shiselweni"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Latitude coordinate", max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Longitude coordinate", max_digits=9
                    ),
                ),
                (
                    "is_affected",
                    models.BooleanField(
                        default=False,
                        help_text="Is this dip tank area affected by FMD?",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of animals this dip tank can serve",
                        null=True,
                    ),
                ),
                (
                    "last_inspection",
                    models.DateTimeField(
                        blank=True, help_text="Last inspection date", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this dip tank"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this dip tank active in the system?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dip Tank",
                "verbose_name_plural": "Dip Tanks",
                "ordering": ["region", "name"],
            },
        ),
    ]
