# Generated by Django 4.2.16 on 2026-02-20 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("outbreaks", "0002_diptank"),
    ]

    operations = [
        migrations.CreateModel(
            name="CordonLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/description of the cordon line", max_length=200
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("hhohho", "Hhohho"),
                            ("manzini", "Manzini"),
                            ("lubombo", "Lubombo"),
                            ("shiselweni", "Shiselweni"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("temporary", "Temporary"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        help_text="Array of coordinate points defining the cordon line"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Purpose and details of this cordon line"
                    ),
                ),
                (
                    "restrictions",
                    models.TextField(
                        blank=True, help_text="Movement restrictions and regulations"
                    ),
                ),
                (
                    "date_established",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this cordon line was established",
                    ),
                ),
                (
                    "date_expires",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this cordon line expires (if temporary)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this cordon line currently active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cordon Line",
                "verbose_name_plural": "Cordon Lines",
                "ordering": ["-date_established"],
            },
        ),
        migrations.CreateModel(
            name="FootWashStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the foot wash station location",
                        max_length=200,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("hhohho", "Hhohho"),
                            ("manzini", "Manzini"),
                            ("lubombo", "Lubombo"),
                            ("shiselweni", "Shiselweni"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "road_name",
                    models.CharField(
                        help_text="Name of the road where station is located",
                        max_length=200,
                    ),
                ),
                (
                    "road_type",
                    models.CharField(
                        choices=[
                            ("highway", "Highway"),
                            ("main_road", "Main Road"),
                            ("secondary_road", "Secondary Road"),
                            ("border_crossing", "Border Crossing"),
                        ],
                        default="main_road",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Latitude coordinate", max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Longitude coordinate", max_digits=9
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Step-by-step instructions for using this station"
                    ),
                ),
                (
                    "operating_hours",
                    models.CharField(
                        default="24/7",
                        help_text="Operating hours of the station",
                        max_length=100,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Contact person at this station",
                        max_length=200,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(
                        default=True, help_text="Is this station currently operational?"
                    ),
                ),
                (
                    "last_maintenance",
                    models.DateTimeField(
                        blank=True, help_text="Last maintenance date", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this station active in the system?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Foot Wash Station",
                "verbose_name_plural": "Foot Wash Stations",
                "ordering": ["region", "road_name", "name"],
            },
        ),
    ]
